# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title title
#'
#' @description
#' description
#'
#'
#' @param x x
#'
#' @details
#'
#' details
#'
#' @return a vector
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @seealso
#' func
#'
#' @examples
#'
#' @export
timesTwo <- function(x) {
    .Call('_IneqCube_timesTwo', PACKAGE = 'IneqCube', x)
}

