# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

flightphase <- function(prob, Xbal) {
    .Call(`_IneqCube_flightphase`, prob, Xbal)
}

#' @title title
#'
#' @description
#' description
#'
#'
#' @param x x
#'
#' @details
#'
#' details
#'
#' @return a vector
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @seealso
#' func
#'
#' @examples
#'
#' @export
flightphase_arma <- function(X, pik, EPS = 0.0000001) {
    .Call(`_IneqCube_flightphase_arma`, X, pik, EPS)
}

#' @title title
#'
#' @description
#' description
#'
#'
#' @param x x
#'
#' @details
#'
#' details
#'
#' @return a vector
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @seealso
#' func
#'
#' @examples
#'
#' @export
onestepflightphase_arma <- function(B, pik, EPS = 0.0000001) {
    .Call(`_IneqCube_onestepflightphase_arma`, B, pik, EPS)
}

#' @title title
#'
#' @description
#' description
#'
#'
#' @param x x
#'
#' @details
#'
#' details
#'
#' @return a vector
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @seealso
#' func
#'
#' @examples
#'
#' @export
rref <- function(M) {
    invisible(.Call(`_IneqCube_rref`, M))
}

