# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title title
#'
#' @description
#' description
#'
#'
#' @param x x
#'
#' @details
#'
#' details
#'
#' @return a vector
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @seealso
#' func
#'
#' @examples
#'
#' @export
rrefBal <- function(M) {
    invisible(.Call(`_IneqCube_rrefBal`, M))
}

#' @title title
#'
#' @description
#' description
#'
#'
#' @param x x
#'
#' @details
#'
#' details
#'
#' @return a vector
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @seealso
#' func
#'
#' @examples
#'
#' @export
onestepfastflightcube <- function(prob, Bm) {
    .Call(`_IneqCube_onestepfastflightcube`, prob, Bm)
}

#' @title title
#'
#' @description
#' description
#'
#'
#' @param x x
#'
#' @details
#'
#' details
#'
#' @return a vector
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @seealso
#' func
#'
#' @examples
#'
#' @export
flightphase <- function(prob, Xbal) {
    .Call(`_IneqCube_flightphase`, prob, Xbal)
}

#' @title title
#'
#' @description
#' description
#'
#'
#' @param x x
#'
#' @details
#'
#' details
#'
#' @return a vector
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @seealso
#' func
#'
#' @examples
#'
#' @export
flightphase_arma <- function(X, pik, EPS = 0.0000001) {
    .Call(`_IneqCube_flightphase_arma`, X, pik, EPS)
}

#' @title title
#'
#' @description
#' description
#'
#'
#' @param x x
#'
#' @details
#'
#' details
#'
#' @return a vector
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @seealso
#' func
#'
#' @examples
#'
#' @export
ineq <- function(X, pik, B, r, EPS = 0.0000001) {
    .Call(`_IneqCube_ineq`, X, pik, B, r, EPS)
}

#' @title title
#'
#' @description
#' description
#'
#'
#' @param x x
#'
#' @details
#'
#' details
#'
#' @return a vector
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @seealso
#' func
#'
#' @examples
#'
#' @export
flightphase_arma2 <- function(X, pik, EPS = 0.0000001) {
    .Call(`_IneqCube_flightphase_arma2`, X, pik, EPS)
}

#' @title title
#'
#' @description
#' description
#'
#'
#' @param x x
#'
#' @details
#'
#' details
#'
#' @return a vector
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @seealso
#' func
#'
#' @examples
#'
#' @export
onestep <- function(B, pik, EPS = 0.0000001) {
    .Call(`_IneqCube_onestep`, B, pik, EPS)
}

#' @title title
#'
#' @description
#' description
#'
#'
#' @param x x
#'
#' @details
#'
#' details
#'
#' @return a vector
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @seealso
#' func
#'
#' @examples
#'
#' @export
onestepineq <- function(Ar, pik, Br, num, EPS = 0.0000001) {
    .Call(`_IneqCube_onestepineq`, Ar, pik, Br, num, EPS)
}

